### ISSUE TITLE
[FEATURE] Support Alternate Ports

### ISSUE THREAD

**Issue by alexfornuto** [ycd/dstp#26]
Thanks for making such a useful tool! It would be swell if it could be used to test services running on alternate ports. Plex, for example, often uses port `32400`:

```
# A standard service listening on 443 with a trusted cert.
❯ dstp https://standardService.myDomain.tld
Ping: 251.027µs
DNS: resolving VALID_IP
SystemDNS: resolving VALID_IP
TLS: certificate is valid for 79 more days
HTTPS: got 200 OK

# A Plex server running remotely on port 32400 with a trusted cert.
❯ dstp https://plex.myDomian.tld:32400
Ping: no response (this is expected from the location this server is running)
DNS: resolving VALID_IP
SystemDNS: resolving VALID_IP
TLS: dial tcp VALID_IP:443: connect: connection timed out
HTTPS: Get "https://plex.myDomain.tld": dial tcp VALID_IP:443: i/o timeout
```

I got the same result passing the URL with the `-a` flag. The expectation is that the tests would use the port provided in this argument where applicable.

**Comment by ycd** [comment]
Hey @alexfornuto, thank you for the suggestion but i don't think it possible to specify a port while sending raw ICMP packets.

To make things clear, ICMP is built on top of IP(Network Layer), which is quite different from TCP and UDP(Transport Layer) since ICMP is considered as layer 3.5 protocol and sits somewhere between Transport Layer and Network Layer and it has no sense of port unlike other Transport Layer protocols since the real reason behind the ports is creating a session between two different processes in different hosts using the source and destination port which is included in the header format for TCP and UDP. 

There are tools like `hping (3)` that you can specify port but they are relying on UDP if you specify the destination port.

**Comment by alexfornuto** [comment]
@ycd thanks for the explanation. To provide additional context, I'm not asking for the ping to look on a port. I understand that's not how ping works, and as I added in the codeblock above the ping failure was expected from this host.

I'm more concerned about the TLS and HTTPS checks checking ports other than 443.

**Comment by ycd** [comment]
@alexfornuto, oh yeah, that's right!

https://github.com/ycd/dstp/blob/a95f470809e8883252bca20eb8ebfd06d65c2254/pkg/dstp/addr.go#L31

The current logic splits the host and port and completely omits the port afterwards. I should and i will add a logic there for specifying different port for HTTPS and TLS. Thanks for bringing this up!

**Comment by ycd** [comment]
Hey @alexfornuto, just implemented this feature and introduced `--port` flag.

**Comment by alexfornuto** [comment]
@ycd Thanks! Confirmed working via brew.
